# Generated by Django 4.2.16 on 2024-12-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cementing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cementing_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('cementing_start_date', models.DateField()),
                ('cementing_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cementing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id_column', models.AutoField(primary_key=True, serialize=False)),
                ('type_column', models.CharField(max_length=20)),
                ('date_installation', models.DateField()),
                ('external_diameter', models.IntegerField()),
            ],
            options={
                'db_table': 'columns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DownholeEquipment',
            fields=[
                ('id_equipment', models.AutoField(primary_key=True, serialize=False)),
                ('type_equipment', models.CharField(max_length=20)),
                ('inner_diameter', models.IntegerField(blank=True, null=True)),
                ('external_diameter', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'downhole_equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perforation',
            fields=[
                ('id_perforation', models.AutoField(primary_key=True, serialize=False)),
                ('сreation_date', models.DateField()),
                ('perforation_densityint', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perforation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tubing',
            fields=[
                ('id_tubing', models.AutoField(primary_key=True, serialize=False)),
                ('descent_date', models.DateField()),
                ('rise_date', models.DateField(blank=True, null=True)),
                ('inner_diameter', models.IntegerField(blank=True, null=True)),
                ('external_diameter', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tubing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id_well', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('wellhead_coordinate_y', models.IntegerField(db_column='wellhead_coordinate_Y')),
                ('wellhead_coordinate_x', models.IntegerField(db_column='wellhead_coordinate_X')),
                ('altitude', models.IntegerField()),
            ],
            options={
                'db_table': 'well',
                'managed': False,
            },
        ),
    ]
